{% set name = "tsl_ordered_map" %}
{% set version = "1.1.0" %}
{% set sha256 = "d6070502351646d68f2bbe6078c0da361bc1db733ee8a392e33cfb8b31183e28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Tessil/ordered-map/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make

test:
  commands:
    - test -d ${PREFIX}/include/tsl  # [unix]
    - test -f ${PREFIX}/include/tsl/ordered_hash.h  # [unix]
    - test -f ${PREFIX}/include/tsl/ordered_map.h  # [unix]
    - test -f ${PREFIX}/include/tsl/ordered_set.h  # [unix]
    - test -f ${PREFIX}/share/cmake/tsl-ordered-map/tsl-ordered-mapConfig.cmake  # [unix]
    - test -f ${PREFIX}/share/cmake/tsl-ordered-map/tsl-ordered-mapTargets.cmake  # [unix]
    - test -f ${PREFIX}/share/cmake/tsl-ordered-map/tsl-ordered-mapConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\tsl\ordered_map.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\tsl_ordered_mapConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\tsl_ordered_mapConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/Tessil/ordered-map
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: C++ ordered hash map and hash set
  description: C++ hash map and hash set which preserve the order of insertion
  doc_url: https://tessil.github.io/ordered-map/
  dev_url: https://github.com/Tessil/ordered-map

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - allanleal
